from instaclient import InstaClient
from instaclient.errors import *

# create the client object
client = InstaClient(driver_path='/usr/bin/chromedriver', localhost_headless=True)

username = input('Enter your instagram username: ')
password = input('Enter your instagram password: ')

# log in with your Instagram credentials
try:
    client.login(username=username, password=password)  # Go through Login Procedure
except VerificationCodeNecessary:
    # This error is raised if the user has 2FA turned on.
    code = input('Enter the 2FA security code generated by your Authenticator App or sent to you by SMS')
    client.input_verification_code(code)
except SuspisciousLoginAttemptError as error:
    # This error is raised by Instagram
    if error.mode == SuspisciousLoginAttemptError.EMAIL:
        code = input('Enter the security code that was sent to you via email: ')
    else:
        code = input('Enter the security code that was sent to you via SMS: ')
    client.input_security_code(code)

# Scrape Instagram followers
username = input('Enter an instagram account\'s username to scrape it\'s followers: ')

try:
    followers = client.get_followers(user=username, count=None, use_api=True)
    print([follower.username for follower in followers[0]])
except InvalidUserError:
    # Exception raised if the username is not valid
    print('The username is not valid')
except PrivateAccountError:
    # Exception raised if the account you are trying to scrape is private
    print('{} is a private account'.format(username))
